# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x10\x65vent_subscriber\"N\n\x10SubscribeRequest\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x03(\x0e\x32\x1b.event_subscriber.EventType\"P\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x0f\n\x07zipCode\x18\x03 \x01(\t\x12\x15\n\rstreetAddress\x18\x04 \x01(\t\"\x89\x01\n\x05\x45vent\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12*\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x19.event_subscriber.Address\x12\x14\n\x0cplacesNumber\x18\x03 \x01(\x05\x12)\n\x04type\x18\x04 \x03(\x0e\x32\x1b.event_subscriber.EventType*a\n\tEventType\x12\x0b\n\x07\x43ONCERT\x10\x00\x12\r\n\tFILM_SHOW\x10\x01\x12\x0c\n\x08\x46OOTBALL\x10\x02\x12\x0e\n\nCLUB_PARTY\x10\x03\x12\x0c\n\x08\x46\x45STIVAL\x10\x04\x12\x0c\n\x08\x41RT_SHOW\x10\x05\x32]\n\x0f\x45ventSubscriber\x12J\n\tsubscribe\x12\".event_subscriber.SubscribeRequest\x1a\x17.event_subscriber.Event0\x01\x42\x1b\n\x0bsr.grpc.genB\nEventProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013sr.grpc.genB\nEventProtoP\001'
  _EVENTTYPE._serialized_start=335
  _EVENTTYPE._serialized_end=432
  _SUBSCRIBEREQUEST._serialized_start=33
  _SUBSCRIBEREQUEST._serialized_end=111
  _ADDRESS._serialized_start=113
  _ADDRESS._serialized_end=193
  _EVENT._serialized_start=196
  _EVENT._serialized_end=333
  _EVENTSUBSCRIBER._serialized_start=434
  _EVENTSUBSCRIBER._serialized_end=527
# @@protoc_insertion_point(module_scope)
